import { createContext } from "react";

const ListsContext = createContext({
  lists: [],
  setLists: () => {},
  tasks: [],
  setTasks: () => {},
  enteredTask: "",
  setEnteredTask: () => {},
  enteredTag: "",
  setEnteredTag: () => {},
  enteredTaskIsValid: false,
  setEnteredTaskIsValid: () => {},
  enteredTaskIsTouched: false,
  setEnteredTaskIsTouched: false,
  enteredList: "",
  setEnteredList: () => {},
  editedEnteredList: "",
  setEditedEnteredList: () => {},
  enteredListIsTouched: false,
  setEnteredListIsTouched: () => {},
  enteredListIsValid: false,
  setEnteredListIsValid: () => {},
  listToEditId: undefined,
  setListToEditId: () => {},
  isLoading: true,
  setIsLoading: () => {},
  editedListIsValid: false,
  setEditedListIsValid: () => {},
  editedListIsTouched: false,
  setEditedListIsTouched: () => {},
  listName: "",
  setListName: () => {},
  calendarIsShown: false,
  setCalendarIsShown: () => {},
  selectedDay: undefined,
  setSelectedDay: () => {},
});

export default ListsContext;
